using namespace std;
#pragma once

//void trafficLightChecker(trafficLights lightColor);
void printNumbers(int incrementalNumber);
void multiplyTable(int numberMultiplied);
int bigSum();
void inputValidator();
void countdown(int start);
void insideLoop();
void arraySetter();
void arrayLoop();
void constExercise();
void plrName();
void stringPrinter(string strInput);
int getStringLength(string strInput);
bool stringComparison(string strInput1, string strInput2);
string stringToLowercase(string strInput);
string stringToUppercase(string strInput);
void gameConfiguration(const string PLAYER_NAME);
void commandParser();
void pointerExercise1();
void pointerExercise2();
void pointerExercise3(int* ptr);
void referenceExercise1();
void doubleValue(int& numInput);
void printValue(const int& numInput);
void writeToFile();
void highscoreFile();
void readHighscoreFile();
void logEvent(string newEvent);
void weaponSelection();